name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/karanimage:latest .
        
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karanimage:latest

      - name: Run Docker container
        run: docker run -d -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/karanimage:latest
