name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

        with:
          context: .
          file: cd karandocker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Build
        uses: docker build -t karanimage .
      -
        name: docker run 
        uses: docker run -d -p 8001:8000 karanimage